In [1]:
import pandas as pd
import numpy as np

In [2]:
path = "/media/jackson/backup/dp_data/tortuosity_study/read_csvs/score_tables/r4_scores.csv"

In [3]:
df = pd.read_csv(path)

In [4]:
df

Tilak  Tuomas  Xavier  BT pred_grade
0        3       3       3              3
1        3       3       3              1
2        1       1       1              1
3        1       1       1              1
4        1       1       1              2
..     ...     ...     ...            ...
162      1       1       2              2
163      3       3       3              3
164      3       3       3              3
165      4       4       4              4
166      1       1       1              1

[167 rows x 4 columns]

In [5]:
arr = df.to_numpy()

In [8]:
all_agree = []
two_agree = []
one_agree = []
none_agree = []

for index, scores in enumerate(arr):
    if np.all(scores[:-1] == scores[-1]):
        all_agree.append(index + 1)
    elif np.sum(scores[:-1] == scores[-1]) == 2:
        two_agree.append(index + 1)
    elif np.sum(scores[:-1] == scores[-1]) == 1:
        one_agree.append(index + 1)
    else:
        none_agree.append(index + 1)

array([  2,   5,  16,  17,  22,  34,  37,  39,  43,  47,  64,  74,  79,
        84,  85,  87,  97, 102, 104, 106, 108, 110, 117, 128, 140, 142,
       155, 160])

In [19]:
l = len(arr)

In [26]:
percents = len(all_agree) / l, len(two_agree) / l, len(one_agree) / l, len(none_agree) / l

In [27]:
np.array(one_agree)

array([  7,  13,  14,  19,  27,  51,  52,  59,  60,  63,  65,  66,  75,
        81,  89,  91, 105, 113, 115, 121, 122, 126, 131, 136, 145, 149,
       156, 163])

In [28]:
np.sum(percents)

1.0

In [29]:
np.array(none_agree)

array([  2,   5,  16,  17,  22,  34,  37,  39,  43,  47,  64,  74,  79,
        84,  85,  87,  97, 102, 104, 106, 108, 110, 117, 128, 140, 142,
       155, 160])